
## Local Test of the Graph Visualisation 

# triples = [
#     ("Kylian Mbappé", "is close to joining", "Real Madrid"),
#     ("Kylian Mbappé", "currently plays for", "Paris Saint-Germain"),
#     ("Kylian Mbappé", "is regarded as", "one of the best forwards"),
#     ("Real Madrid", "have pursued", "Kylian Mbappé for years"),
#     ("Real Madrid", "offered", "record-breaking contract"),
#     ("Contract offer", "includes", "performance-based bonuses"),
#     ("Mbappé's entourage", "negotiated with", "Real Madrid representatives"),
#     ("Paris Saint-Germain", "attempted to renew", "Mbappé's contract"),
#     ("Mbappé", "rejected", "PSG’s final extension offer"),
#     ("PSG", "fear losing", "Mbappé on free transfer"),
#     ("Mbappé", "was signed from", "Monaco"),
#     ("Real Madrid", "have scouted", "Mbappé extensively"),
#     ("Mbappé", "has admiration for", "Zinedine Zidane"),
#     ("Zidane", "was", "Real Madrid legend"),
#     ("Mbappé", "grew up watching", "Cristiano Ronaldo at Real Madrid"),
#     ("Mbappé", "believes move will boost", "Ballon d'Or chances"),
#     ("Mbappé", "scored", "42 goals this season"),
#     ("PSG", "value Mbappé at", "€200 million"),
#     ("Real Madrid", "prefer to wait for", "contract expiration"),
#     ("Mbappé’s contract", "expires in", "July 2025"),
#     ("Real Madrid board", "divided over", "paying fee or waiting"),
#     ("Mbappé", "could wear", "number 7 jersey at Madrid"),
#     ("Vinicius Jr", "currently wears", "number 7 jersey"),
#     ("Ancelotti", "approves", "Mbappé signing"),
#     ("Florentino Pérez", "personally involved in", "Mbappé deal"),
#     ("Mbappé’s mother", "acts as", "his agent"),
#     ("Mbappé", "demands", "image rights control"),
#     ("Image rights", "complicate", "contract negotiations"),
#     ("Real Madrid", "typically retain", "50% image rights"),
#     ("Mbappé", "wants to play in", "Champions League final"),
#     ("Mbappé", "hopes to join before", "preseason tour in Asia"),
#     ("Real Madrid", "planning medical in", "Madrid"),
#     ("PSG", "refuse to release", "Mbappé early"),
#     ("FIFA regulations", "allow", "pre-contract agreement"),
#     ("Mbappé", "already signed", "pre-contract with Madrid"),
#     ("Mbappé", "expected to debut in", "El Clásico"),
#     ("Barcelona", "aware of", "Madrid's plans"),
#     ("Barcelona president", "criticized", "Mbappé's high wages"),
#     ("Mbappé", "remains focused on", "PSG’s current campaign"),
#     ("Mbappé", "was benched in", "last league match"),
#     ("PSG coach", "refused to comment on", "Mbappé’s future"),
#     ("Mbappé", "publicly thanked", "PSG fans"),
#     ("PSG ultras", "unhappy with", "Mbappé's decision"),
#     ("Mbappé", "will earn", "€25 million annually"),
#     ("Contract duration", "expected to be", "5 years"),
#     ("Madrid fans", "excited by", "Mbappé’s potential arrival"),
#     ("Spanish media", "report daily updates on", "Mbappé transfer saga"),
#     ("Mbappé", "will attend", "official unveiling at Bernabéu"),
#     ("Presentation event", "planned for", "mid-July"),
#     ("Mbappé", "may join", "Olympic squad for France"),
#     ("Real Madrid", "unwilling to release", "player for Olympics"),
#     ("Olympic participation", "not mandatory under", "FIFA rules"),
#     ("Mbappé", "likely to skip", "Paris 2024 Olympics"),
#     ("Mbappé", "expects", "warm reception from Madrid fans")
# ]


# gp = GraphPlot()
# gp.plot(triples)